version: '3.7'
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
      - MSSQL_PID=Express
    container_name: mssql
    restart: unless-stopped
    volumes:
      - mssql:/var/opt/mssql
    networks: 
      - bankanalizer_network

  bankanalizer-backend:
    container_name: bankanalizer-backend
    build:
      context: ./backend/BankAnalizer
      dockerfile: Dockerfile.prod
    ports:
      - '4444:4444'
    depends_on: 
      - mssql
    networks: 
      - bankanalizer_network

  bankanalizer-frontend:
    container_name: bankanalizer-frontend
    build:
      context: ./frontend/bankanalizer
      dockerfile: Dockerfile.prod
    ports:
      - '3333:80'
    depends_on: 
      - bankanalizer-backend

networks:
  bankanalizer_network:
    driver: bridge

volumes:
  mssql:
