version: '3'
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
      - MSSQL_PID=Express
    container_name: mssql
    restart: unless-stopped